# Generated by Django 3.0.14 on 2022-07-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0004_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='days',
            field=models.TextField(default='All', max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='mods_link',
            field=models.TextField(default='', max_length=400),
        ),
    ]
