# Generated by Django 3.0.14 on 2022-07-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeslots', '0005_auto_20220712_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='gym_name',
            field=models.TextField(default='UTown', max_length=256),
        ),
    ]
